version: '3.7'

services:
  webserver:
    build:
      context: .
      dockerfile: ./webserver/Dockerfile
    command: gunicorn -b 0.0.0.0:5000 webserver_entrypoint:app
    volumes:
      - ./:/usr/src/webserver/
    ports:
      - 5000:5000