apiVersion: v1
kind: PersistentVolume
metadata:
  name: config-pv
spec:
  capacity:
    storage: 100M
  storageClassName: config
  accessModes:
    - ReadOnlyMany
  hostPath:
    #where the config will be mounted
    path: "/mnt/config/"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: config-pvc
  labels:
    type: local
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: config
  resources:
    requests:
      storage: 100M
  volumeName: config-pv
  

      #   volumeMounts:
      #   - mountPath: /mnt/config
      #     name: config-pvc-storage
      # dnsPolicy: ClusterFirst
      # restartPolicy: Always
      # schedulerName: default-scheduler
      # securityContext: {}
      # terminationGracePeriodSeconds: 30
      # volumes:
      # - name: config-pvc-storage
      #   persistentVolumeClaim:
      #     claimName: config-pvc
