apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: update_butler
  name: update_butler
  namespace: default
spec:
  schedule: "0 3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: update_butler
            image: trainconnectionprediction/tcp:update_butler
            imagePullPolicy: Always
            volumeMounts:
            - name: config-pvc-storage
              mountPath: /mnt/config  
            - name: cache-pvc-storage
              mountPath: /usr/src/app/cache   
          restartPolicy: OnFailure
          volumes:
          - name: config-pvc-storage
            persistentVolumeClaim:
              claimName: config-pvc
          - name: cache-pvc-storage
            persistentVolumeClaim:
              claimName: cache-pvc
