
# ICE / Fernverkehr mit Triebfahrzeug
standarts = {
    'fernverkehr_mit_triebfahrzeug': {
        "wegpunkte":[
            {
                "betriebsstelle":{
                    "ds100":"TT", # Bahnhof Start
                    "mutter":False
                },
                "zugcharakteristik":{
                    "triebfahrzeug":{
                        "hauptnummer":"401",
                        "unternummer":10,
                        "kennung":"U",
                        "kennung_wert":8000
                    },
                    "vorspannart":"ohne",
                    "zugbeeinflussung":"PZB/LZB/ETCS",
                    "wagenzuglaenge_m":0,
                    "wagenzugmasse_t":0,
                    "v_max":300,
                    "bremshundertstel":200,
                    "bremsstellung":"R+Mg",
                    "kv_profil":{
                        "c":"N",
                        "p":"N"
                    },
                    "streckenklasse":"C2",
                    "fuehrendes_fahrzeug":"triebwagen",
                    "aktive_neigetechnik":False,
                    "nachschiebeart":"ohne",
                    "nachschiebe_druckkraft":"kn_240"
                }
            },
            {
                "betriebsstelle":{
                    "ds100":"TS", # Bahnhof Ziel
                    "mutter":False
                }
            }
        ],
        "sucheinstellungen":{
            "verkehrsart":"spfv_tw",
            "abfahrtszeit":"2020-03-19T14:50:00+01:00",
            "alternative_routen":False,
            "richtungswechsel_zulaessig":True,
            "vermeidung_parameter":{
                "ueberlastete_meiden":False,
                "sbahnen_meiden":True,
                "nebenbahnen_meiden":True,
                "schnellfahrstrecken_meiden":False,
                "knotenbahnhoefe_meiden":False,
                "notbremsueberbrueckung_meiden":False,
                "wirbelstrombremse_meiden":False,
                "eingleisige_strecken_meiden":True
            },
            "initiale_sperrungen_beruecksichtigen":True,
            "wendezeit_min":5,
            "mit_realistischen_fahrzeiten_optimieren":False,
            "verkehrshalte_nur_an_bahnsteigen":True,
            "einschraenkungen_beachten":True,
            "manueller_fahrzeitzuschlag_prozent":5,
            "einzelgrenzlastberechnung_zulaessig":False,
            "bauzuschlaege_beachten":False,
            "laengenabhaengige_grenzlasten_verwenden":False,
            "gewichtung_parameter":{
                "streckenlaenge_prozent":30,
                "fahrzeit_prozent":50,
                "energie_prozent":20
            },
            "zusatzkosten_parameter":{
                "energiebezugspreis_euro_pro_kwh":0.18,
                "rueckspeisung_euro_pro_kwh":0.09,
                "kosten_fahrzeuge_personal_euro_pro_h":1000
            },
            "trassenentgelt_parameter":{
                "marktsegment":"spfv_metro_tag_basic_nacht",
                "flexibilitaet":"kein_flex",
                "prioritaet":"keine_prioritaet",
                "gefahrgutganzzug":False
            }
        },
        "nutzer_sperrungen":[
        ]
    },

    # IC / Fernverkehr mit Lok
    # {"wegpunkte":[{"betriebsstelle":{"ds100":"TT","mutter":False},"zugcharakteristik":{"triebfahrzeug":{"hauptnummer":"6182","unternummer":1,"kennung":"L","kennung_wert":80},"vorspannart":"ohne","zugbeeinflussung":"PZB/LZB","wagenzuglaenge_m":212,"wagenzugmasse_t":360,"v_max":200,"bremshundertstel":200,"bremsstellung":"R+Mg","kv_profil":{"c":"N","p":"N"},"streckenklasse":"D2","fuehrendes_fahrzeug":"lokomotive","aktive_neigetechnik":False,"nachschiebeart":"ohne","nachschiebe_druckkraft":"kn_240"}},{"betriebsstelle":{"ds100":"TS","mutter":False}}],"sucheinstellungen":{"verkehrsart":"spfv_lok","abfahrtszeit":"2020-03-19T16:12:00+01:00","alternative_routen":False,"richtungswechsel_zulaessig":True,"vermeidung_parameter":{"ueberlastete_meiden":False,"sbahnen_meiden":True,"nebenbahnen_meiden":True,"schnellfahrstrecken_meiden":False,"knotenbahnhoefe_meiden":False,"notbremsueberbrueckung_meiden":False,"wirbelstrombremse_meiden":False,"eingleisige_strecken_meiden":True},"initiale_sperrungen_beruecksichtigen":True,"wendezeit_min":5,"mit_realistischen_fahrzeiten_optimieren":False,"verkehrshalte_nur_an_bahnsteigen":True,"einschraenkungen_beachten":True,"manueller_fahrzeitzuschlag_prozent":5,"einzelgrenzlastberechnung_zulaessig":False,"bauzuschlaege_beachten":False,"laengenabhaengige_grenzlasten_verwenden":False,"gewichtung_parameter":{"streckenlaenge_prozent":30,"fahrzeit_prozent":50,"energie_prozent":20},"zusatzkosten_parameter":{"energiebezugspreis_euro_pro_kwh":0.18,"rueckspeisung_euro_pro_kwh":0.09,"kosten_fahrzeuge_personal_euro_pro_h":600},"trassenentgelt_parameter":{"marktsegment":"spfv_metro_tag_basic_nacht","flexibilitaet":"kein_flex","prioritaet":"keine_prioritaet","gefahrgutganzzug":False}},"nutzer_sperrungen":[]}
    'fernverkehr_mit_lok': {
        "wegpunkte":[
            {
                "betriebsstelle":{
                    "ds100":"TT",
                    "mutter":False
                },
                "zugcharakteristik":{
                    "triebfahrzeug":{
                        "hauptnummer":"6182",
                        "unternummer":1,
                        "kennung":"L",
                        "kennung_wert":80
                    },
                    "vorspannart":"ohne",
                    "zugbeeinflussung":"PZB/LZB",
                    "wagenzuglaenge_m":212,
                    "wagenzugmasse_t":360,
                    "v_max":200,
                    "bremshundertstel":200,
                    "bremsstellung":"R+Mg",
                    "kv_profil":{
                        "c":"N",
                        "p":"N"
                    },
                    "streckenklasse":"D2",
                    "fuehrendes_fahrzeug":"lokomotive",
                    "aktive_neigetechnik":False,
                    "nachschiebeart":"ohne",
                    "nachschiebe_druckkraft":"kn_240"
                }
            },
            {
                "betriebsstelle":{
                    "ds100":"TS",
                    "mutter":False
                }
            }
        ],
        "sucheinstellungen":{
            "verkehrsart":"spfv_lok",
            "abfahrtszeit":"2020-03-19T16:12:00+01:00",
            "alternative_routen":False,
            "richtungswechsel_zulaessig":True,
            "vermeidung_parameter":{
                "ueberlastete_meiden":False,
                "sbahnen_meiden":True,
                "nebenbahnen_meiden":True,
                "schnellfahrstrecken_meiden":False,
                "knotenbahnhoefe_meiden":False,
                "notbremsueberbrueckung_meiden":False,
                "wirbelstrombremse_meiden":False,
                "eingleisige_strecken_meiden":True
            },
            "initiale_sperrungen_beruecksichtigen":True,
            "wendezeit_min":5,
            "mit_realistischen_fahrzeiten_optimieren":False,
            "verkehrshalte_nur_an_bahnsteigen":True,
            "einschraenkungen_beachten":True,
            "manueller_fahrzeitzuschlag_prozent":5,
            "einzelgrenzlastberechnung_zulaessig":False,
            "bauzuschlaege_beachten":False,
            "laengenabhaengige_grenzlasten_verwenden":False,
            "gewichtung_parameter":{
                "streckenlaenge_prozent":30,
                "fahrzeit_prozent":50,
                "energie_prozent":20
            },
            "zusatzkosten_parameter":{
                "energiebezugspreis_euro_pro_kwh":0.18,
                "rueckspeisung_euro_pro_kwh":0.09,
                "kosten_fahrzeuge_personal_euro_pro_h":600
            },
            "trassenentgelt_parameter":{
                "marktsegment":"spfv_metro_tag_basic_nacht",
                "flexibilitaet":"kein_flex",
                "prioritaet":"keine_prioritaet",
                "gefahrgutganzzug":False
            }
        },
        "nutzer_sperrungen":[

        ]
    },

    # Nahverkehr mit Lok
    # {"wegpunkte":[{"betriebsstelle":{"ds100":"TT","mutter":False},"zugcharakteristik":{"triebfahrzeug":{"hauptnummer":"6146","unternummer":3,"kennung":"L","kennung_wert":80},"vorspannart":"ohne","zugbeeinflussung":"PZB/LZB","wagenzuglaenge_m":132,"wagenzugmasse_t":225,"v_max":160,"bremshundertstel":160,"bremsstellung":"R+Mg","kv_profil":{"c":"N","p":"N"},"streckenklasse":"C2","fuehrendes_fahrzeug":"lokomotive","aktive_neigetechnik":False,"nachschiebeart":"ohne","nachschiebe_druckkraft":"kn_240"}},{"betriebsstelle":{"ds100":"TS","mutter":False}}],"sucheinstellungen":{"verkehrsart":"spnv_lok","abfahrtszeit":"2020-03-19T16:18:00+01:00","alternative_routen":False,"richtungswechsel_zulaessig":True,"vermeidung_parameter":{"ueberlastete_meiden":False,"sbahnen_meiden":False,"nebenbahnen_meiden":False,"schnellfahrstrecken_meiden":True,"knotenbahnhoefe_meiden":False,"notbremsueberbrueckung_meiden":False,"wirbelstrombremse_meiden":False,"eingleisige_strecken_meiden":False},"initiale_sperrungen_beruecksichtigen":True,"wendezeit_min":5,"mit_realistischen_fahrzeiten_optimieren":False,"verkehrshalte_nur_an_bahnsteigen":True,"einschraenkungen_beachten":True,"manueller_fahrzeitzuschlag_prozent":5,"einzelgrenzlastberechnung_zulaessig":False,"bauzuschlaege_beachten":False,"laengenabhaengige_grenzlasten_verwenden":False,"gewichtung_parameter":{"streckenlaenge_prozent":30,"fahrzeit_prozent":50,"energie_prozent":20},"zusatzkosten_parameter":{"energiebezugspreis_euro_pro_kwh":0.18,"rueckspeisung_euro_pro_kwh":0.09,"kosten_fahrzeuge_personal_euro_pro_h":300},"trassenentgelt_parameter":{"marktsegment":"spnv_lastfahrt","flexibilitaet":"kein_flex","prioritaet":"keine_prioritaet","gefahrgutganzzug":False}},"nutzer_sperrungen":[]}

    'nahverkehr_mit_lok': {
        "wegpunkte":[
            {
                "betriebsstelle":{
                    "ds100":"TT",
                    "mutter":False
                },
                "zugcharakteristik":{
                    "triebfahrzeug":{
                        "hauptnummer":"6146",
                        "unternummer":3,
                        "kennung":"L",
                        "kennung_wert":80
                    },
                    "vorspannart":"ohne",
                    "zugbeeinflussung":"PZB/LZB",
                    "wagenzuglaenge_m":132,
                    "wagenzugmasse_t":225,
                    "v_max":160,
                    "bremshundertstel":160,
                    "bremsstellung":"R+Mg",
                    "kv_profil":{
                        "c":"N",
                        "p":"N"
                    },
                    "streckenklasse":"C2",
                    "fuehrendes_fahrzeug":"lokomotive",
                    "aktive_neigetechnik":False,
                    "nachschiebeart":"ohne",
                    "nachschiebe_druckkraft":"kn_240"
                }
            },
            {
                "betriebsstelle":{
                    "ds100":"TS",
                    "mutter":False
                }
            }
        ],
        "sucheinstellungen":{
            "verkehrsart":"spnv_lok",
            "abfahrtszeit":"2020-03-19T16:18:00+01:00",
            "alternative_routen":False,
            "richtungswechsel_zulaessig":True,
            "vermeidung_parameter":{
                "ueberlastete_meiden":False,
                "sbahnen_meiden":False,
                "nebenbahnen_meiden":False,
                "schnellfahrstrecken_meiden":True,
                "knotenbahnhoefe_meiden":False,
                "notbremsueberbrueckung_meiden":False,
                "wirbelstrombremse_meiden":False,
                "eingleisige_strecken_meiden":False
            },
            "initiale_sperrungen_beruecksichtigen":True,
            "wendezeit_min":5,
            "mit_realistischen_fahrzeiten_optimieren":False,
            "verkehrshalte_nur_an_bahnsteigen":True,
            "einschraenkungen_beachten":True,
            "manueller_fahrzeitzuschlag_prozent":5,
            "einzelgrenzlastberechnung_zulaessig":False,
            "bauzuschlaege_beachten":False,
            "laengenabhaengige_grenzlasten_verwenden":False,
            "gewichtung_parameter":{
                "streckenlaenge_prozent":30,
                "fahrzeit_prozent":50,
                "energie_prozent":20
            },
            "zusatzkosten_parameter":{
                "energiebezugspreis_euro_pro_kwh":0.18,
                "rueckspeisung_euro_pro_kwh":0.09,
                "kosten_fahrzeuge_personal_euro_pro_h":300
            },
            "trassenentgelt_parameter":{
                "marktsegment":"spnv_lastfahrt",
                "flexibilitaet":"kein_flex",
                "prioritaet":"keine_prioritaet",
                "gefahrgutganzzug":False
            }
        },
        "nutzer_sperrungen":[

        ]
    },

    # Nahverkehr mit Triebfahrzeug
    # {"wegpunkte":[{"betriebsstelle":{"ds100":"TT","mutter":False},"zugcharakteristik":{"triebfahrzeug":{"hauptnummer":"442","unternummer":9,"kennung":"U","kennung_wert":8000},"vorspannart":"ohne","zugbeeinflussung":"PZB/LZB","wagenzuglaenge_m":0,"wagenzugmasse_t":0,"v_max":160,"bremshundertstel":160,"bremsstellung":"R+Mg","kv_profil":{"c":"N","p":"N"},"streckenklasse":"B1","fuehrendes_fahrzeug":"triebwagen","aktive_neigetechnik":False,"nachschiebeart":"ohne","nachschiebe_druckkraft":"kn_240"}},{"betriebsstelle":{"ds100":"TS","mutter":False}}],"sucheinstellungen":{"verkehrsart":"spnv_tw","abfahrtszeit":"2020-03-19T16:19:00+01:00","alternative_routen":False,"richtungswechsel_zulaessig":True,"vermeidung_parameter":{"ueberlastete_meiden":False,"sbahnen_meiden":False,"nebenbahnen_meiden":False,"schnellfahrstrecken_meiden":True,"knotenbahnhoefe_meiden":False,"notbremsueberbrueckung_meiden":False,"wirbelstrombremse_meiden":False,"eingleisige_strecken_meiden":False},"initiale_sperrungen_beruecksichtigen":True,"wendezeit_min":5,"mit_realistischen_fahrzeiten_optimieren":False,"verkehrshalte_nur_an_bahnsteigen":True,"einschraenkungen_beachten":True,"manueller_fahrzeitzuschlag_prozent":5,"einzelgrenzlastberechnung_zulaessig":False,"bauzuschlaege_beachten":False,"laengenabhaengige_grenzlasten_verwenden":False,"gewichtung_parameter":{"streckenlaenge_prozent":30,"fahrzeit_prozent":50,"energie_prozent":20},"zusatzkosten_parameter":{"energiebezugspreis_euro_pro_kwh":0.18,"rueckspeisung_euro_pro_kwh":0.09,"kosten_fahrzeuge_personal_euro_pro_h":500},"trassenentgelt_parameter":{"marktsegment":"spnv_lastfahrt","flexibilitaet":"kein_flex","prioritaet":"keine_prioritaet","gefahrgutganzzug":False}},"nutzer_sperrungen":[]}

    'nahverkehr_mit_triebfahrzeug': {
        "wegpunkte":[
            {
                "betriebsstelle":{
                    "ds100":"TT",
                    "mutter":False
                },
                "zugcharakteristik":{
                    "triebfahrzeug":{
                        "hauptnummer":"442",
                        "unternummer":9,
                        "kennung":"U",
                        "kennung_wert":8000
                    },
                    "vorspannart":"ohne",
                    "zugbeeinflussung":"PZB/LZB",
                    "wagenzuglaenge_m":0,
                    "wagenzugmasse_t":0,
                    "v_max":160,
                    "bremshundertstel":160,
                    "bremsstellung":"R+Mg",
                    "kv_profil":{
                        "c":"N",
                        "p":"N"
                    },
                    "streckenklasse":"B1",
                    "fuehrendes_fahrzeug":"triebwagen",
                    "aktive_neigetechnik":False,
                    "nachschiebeart":"ohne",
                    "nachschiebe_druckkraft":"kn_240"
                }
            },
            {
                "betriebsstelle":{
                    "ds100":"TS",
                    "mutter":False
                }
            }
        ],
        "sucheinstellungen":{
            "verkehrsart":"spnv_tw",
            "abfahrtszeit":"2020-03-19T16:19:00+01:00",
            "alternative_routen":False,
            "richtungswechsel_zulaessig":True,
            "vermeidung_parameter":{
                "ueberlastete_meiden":False,
                "sbahnen_meiden":False,
                "nebenbahnen_meiden":False,
                "schnellfahrstrecken_meiden":True,
                "knotenbahnhoefe_meiden":False,
                "notbremsueberbrueckung_meiden":False,
                "wirbelstrombremse_meiden":False,
                "eingleisige_strecken_meiden":False
            },
            "initiale_sperrungen_beruecksichtigen":True,
            "wendezeit_min":5,
            "mit_realistischen_fahrzeiten_optimieren":False,
            "verkehrshalte_nur_an_bahnsteigen":True,
            "einschraenkungen_beachten":True,
            "manueller_fahrzeitzuschlag_prozent":5,
            "einzelgrenzlastberechnung_zulaessig":False,
            "bauzuschlaege_beachten":False,
            "laengenabhaengige_grenzlasten_verwenden":False,
            "gewichtung_parameter":{
                "streckenlaenge_prozent":30,
                "fahrzeit_prozent":50,
                "energie_prozent":20
            },
            "zusatzkosten_parameter":{
                "energiebezugspreis_euro_pro_kwh":0.18,
                "rueckspeisung_euro_pro_kwh":0.09,
                "kosten_fahrzeuge_personal_euro_pro_h":500
            },
            "trassenentgelt_parameter":{
                "marktsegment":"spnv_lastfahrt",
                "flexibilitaet":"kein_flex",
                "prioritaet":"keine_prioritaet",
                "gefahrgutganzzug":False
            }
        },
        "nutzer_sperrungen":[

        ]
    },

    # S-Bahn
    # {"wegpunkte":[{"betriebsstelle":{"ds100":"TT","mutter":False},"zugcharakteristik":{"triebfahrzeug":{"hauptnummer":"423","unternummer":2,"kennung":"U","kennung_wert":8000},"vorspannart":"ohne","zugbeeinflussung":"PZB","wagenzuglaenge_m":0,"wagenzugmasse_t":0,"v_max":140,"bremshundertstel":160,"bremsstellung":"R+Mg","kv_profil":{"c":"N","p":"N"},"streckenklasse":"B1","fuehrendes_fahrzeug":"triebwagen","aktive_neigetechnik":False,"nachschiebeart":"ohne","nachschiebe_druckkraft":"kn_240"}},{"betriebsstelle":{"ds100":"TS","mutter":False}}],"sucheinstellungen":{"verkehrsart":"sbahn","abfahrtszeit":"2020-03-19T16:21:00+01:00","alternative_routen":False,"richtungswechsel_zulaessig":False,"vermeidung_parameter":{"ueberlastete_meiden":False,"sbahnen_meiden":False,"nebenbahnen_meiden":True,"schnellfahrstrecken_meiden":True,"knotenbahnhoefe_meiden":False,"notbremsueberbrueckung_meiden":False,"wirbelstrombremse_meiden":False,"eingleisige_strecken_meiden":True},"initiale_sperrungen_beruecksichtigen":True,"wendezeit_min":5,"mit_realistischen_fahrzeiten_optimieren":False,"verkehrshalte_nur_an_bahnsteigen":True,"einschraenkungen_beachten":True,"manueller_fahrzeitzuschlag_prozent":5,"einzelgrenzlastberechnung_zulaessig":False,"bauzuschlaege_beachten":False,"laengenabhaengige_grenzlasten_verwenden":False,"gewichtung_parameter":{"streckenlaenge_prozent":30,"fahrzeit_prozent":50,"energie_prozent":20},"zusatzkosten_parameter":{"energiebezugspreis_euro_pro_kwh":0.18,"rueckspeisung_euro_pro_kwh":0.09,"kosten_fahrzeuge_personal_euro_pro_h":500},"trassenentgelt_parameter":{"marktsegment":"spnv_lastfahrt","flexibilitaet":"kein_flex","prioritaet":"keine_prioritaet","gefahrgutganzzug":False}},"nutzer_sperrungen":[]}

    's_bahn': {
        "wegpunkte":[
            {
                "betriebsstelle":{
                    "ds100":"TT",
                    "mutter":False
                },
                "zugcharakteristik":{
                    "triebfahrzeug":{
                        "hauptnummer":"423",
                        "unternummer":2,
                        "kennung":"U",
                        "kennung_wert":8000
                    },
                    "vorspannart":"ohne",
                    "zugbeeinflussung":"PZB",
                    "wagenzuglaenge_m":0,
                    "wagenzugmasse_t":0,
                    "v_max":140,
                    "bremshundertstel":160,
                    "bremsstellung":"R+Mg",
                    "kv_profil":{
                        "c":"N",
                        "p":"N"
                    },
                    "streckenklasse":"B1",
                    "fuehrendes_fahrzeug":"triebwagen",
                    "aktive_neigetechnik":False,
                    "nachschiebeart":"ohne",
                    "nachschiebe_druckkraft":"kn_240"
                }
            },
            {
                "betriebsstelle":{
                    "ds100":"TS",
                    "mutter":False
                }
            }
        ],
        "sucheinstellungen":{
            "verkehrsart":"sbahn",
            "abfahrtszeit":"2020-03-19T16:21:00+01:00",
            "alternative_routen":False,
            "richtungswechsel_zulaessig":False,
            "vermeidung_parameter":{
                "ueberlastete_meiden":False,
                "sbahnen_meiden":False,
                "nebenbahnen_meiden":True,
                "schnellfahrstrecken_meiden":True,
                "knotenbahnhoefe_meiden":False,
                "notbremsueberbrueckung_meiden":False,
                "wirbelstrombremse_meiden":False,
                "eingleisige_strecken_meiden":True
            },
            "initiale_sperrungen_beruecksichtigen":True,
            "wendezeit_min":5,
            "mit_realistischen_fahrzeiten_optimieren":False,
            "verkehrshalte_nur_an_bahnsteigen":True,
            "einschraenkungen_beachten":True,
            "manueller_fahrzeitzuschlag_prozent":5,
            "einzelgrenzlastberechnung_zulaessig":False,
            "bauzuschlaege_beachten":False,
            "laengenabhaengige_grenzlasten_verwenden":False,
            "gewichtung_parameter":{
                "streckenlaenge_prozent":30,
                "fahrzeit_prozent":50,
                "energie_prozent":20
            },
            "zusatzkosten_parameter":{
                "energiebezugspreis_euro_pro_kwh":0.18,
                "rueckspeisung_euro_pro_kwh":0.09,
                "kosten_fahrzeuge_personal_euro_pro_h":500
            },
            "trassenentgelt_parameter":{
                "marktsegment":"spnv_lastfahrt",
                "flexibilitaet":"kein_flex",
                "prioritaet":"keine_prioritaet",
                "gefahrgutganzzug":False
            }
        },
        "nutzer_sperrungen":[
        ]
    },

    'fernverkehr_diesel_lok': {
        "wegpunkte":[
            {
                "betriebsstelle":{
                    "ds100":"TT",
                    "mutter":False
                },
                "zugcharakteristik":{
                    "triebfahrzeug":{
                        "hauptnummer":"218",
                        "unternummer":3,
                        "kennung":"U",
                        "kennung_wert":8000
                    },
                    "vorspannart":"ohne",
                    "zugbeeinflussung":"PZB/LZB",
                    "wagenzuglaenge_m":212,
                    "wagenzugmasse_t":360,
                    "v_max":140,
                    "bremshundertstel":200,
                    "bremsstellung":"R+Mg",
                    "kv_profil":{
                        "c":"N",
                        "p":"N"
                    },
                    "streckenklasse":"D2",
                    "fuehrendes_fahrzeug":"lokomotive",
                    "aktive_neigetechnik":False,
                    "nachschiebeart":"ohne",
                    "nachschiebe_druckkraft":"kn_240"
                }
            },
            {
                "betriebsstelle":{
                    "ds100":"KK",
                    "mutter":False
                }
            }
        ],
        "sucheinstellungen":{
            "verkehrsart":"spfv_lok",
            "abfahrtszeit":"2020-04-28T01:45:00+02:00",
            "alternative_routen":False,
            "richtungswechsel_zulaessig":True,
            "vermeidung_parameter":{
                "ueberlastete_meiden":False,
                "sbahnen_meiden":True,
                "nebenbahnen_meiden":True,
                "schnellfahrstrecken_meiden":False,
                "knotenbahnhoefe_meiden":False,
                "notbremsueberbrueckung_meiden":False,
                "wirbelstrombremse_meiden":False,
                "eingleisige_strecken_meiden":True
            },
            "initiale_sperrungen_beruecksichtigen":True,
            "wendezeit_min":5,
            "mit_realistischen_fahrzeiten_optimieren":False,
            "verkehrshalte_nur_an_bahnsteigen":True,
            "einschraenkungen_beachten":True,
            "manueller_fahrzeitzuschlag_prozent":5,
            "einzelgrenzlastberechnung_zulaessig":False,
            "bauzuschlaege_beachten":False,
            "laengenabhaengige_grenzlasten_verwenden":False,
            "gewichtung_parameter":{
                "streckenlaenge_prozent":30,
                "fahrzeit_prozent":50,
                "energie_prozent":20
            },
            "zusatzkosten_parameter":{
                "energiebezugspreis_euro_pro_kwh":0.18,
                "rueckspeisung_euro_pro_kwh":0.09,
                "kosten_fahrzeuge_personal_euro_pro_h":600
            },
            "trassenentgelt_parameter":{
                "marktsegment":"spfv_metro_tag_basic_nacht",
                "flexibilitaet":"kein_flex",
                "prioritaet":"keine_prioritaet",
                "gefahrgutganzzug":False
            }
        },
        "nutzer_sperrungen":[

        ]
    },

    "nahverkehr_diesel_lok": {
        "wegpunkte":[
            {
                "betriebsstelle":{
                    "ds100":"EDO",
                    "mutter":False
                },
                "zugcharakteristik":{
                    "triebfahrzeug":{
                        "hauptnummer":"ER 20D",
                        "unternummer":2,
                        "kennung":"N",
                        "kennung_wert":999
                    },
                    "vorspannart":"ohne",
                    "zugbeeinflussung":"PZB/LZB",
                    "wagenzuglaenge_m":132,
                    "wagenzugmasse_t":225,
                    "v_max":140,
                    "bremshundertstel":160,
                    "bremsstellung":"R+Mg",
                    "kv_profil":{
                        "c":"N",
                        "p":"N"
                    },
                    "streckenklasse":"C2",
                    "fuehrendes_fahrzeug":"lokomotive",
                    "aktive_neigetechnik":False,
                    "nachschiebeart":"ohne",
                    "nachschiebe_druckkraft":"kn_240"
                }
            },
            {
                "betriebsstelle":{
                    "ds100":"TT",
                    "mutter":False
                }
            }
        ],
        "sucheinstellungen":{
            "verkehrsart":"spnv_lok",
            "abfahrtszeit":"2020-04-28T02:08:00+02:00",
            "alternative_routen":False,
            "richtungswechsel_zulaessig":True,
            "vermeidung_parameter":{
                "ueberlastete_meiden":False,
                "sbahnen_meiden":False,
                "nebenbahnen_meiden":False,
                "schnellfahrstrecken_meiden":True,
                "knotenbahnhoefe_meiden":False,
                "notbremsueberbrueckung_meiden":False,
                "wirbelstrombremse_meiden":False,
                "eingleisige_strecken_meiden":False
            },
            "initiale_sperrungen_beruecksichtigen":True,
            "wendezeit_min":5,
            "mit_realistischen_fahrzeiten_optimieren":False,
            "verkehrshalte_nur_an_bahnsteigen":True,
            "einschraenkungen_beachten":True,
            "manueller_fahrzeitzuschlag_prozent":5,
            "einzelgrenzlastberechnung_zulaessig":False,
            "bauzuschlaege_beachten":False,
            "laengenabhaengige_grenzlasten_verwenden":False,
            "gewichtung_parameter":{
                "streckenlaenge_prozent":30,
                "fahrzeit_prozent":50,
                "energie_prozent":20
            },
            "zusatzkosten_parameter":{
                "energiebezugspreis_euro_pro_kwh":0.18,
                "rueckspeisung_euro_pro_kwh":0.09,
                "kosten_fahrzeuge_personal_euro_pro_h":300
            },
            "trassenentgelt_parameter":{
                "marktsegment":"spnv_lastfahrt",
                "flexibilitaet":"kein_flex",
                "prioritaet":"keine_prioritaet",
                "gefahrgutganzzug":False
            }
        },
        "nutzer_sperrungen":[

        ]
    }
}