name: "Build and Push Docker images to Docker Hub"

on:
  push:
    branches:
      - 'master'

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push webserver
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: webserver/Dockerfile.webserver
          tags: trainconnectionprediction/webserver:latest

      - name: Build and push update_butler
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          file: update_butler/Dockerfile.update_butler
          tags: trainconnectionprediction/tcp:update_butler
