name: Test and Deploy

# Controls when the action will run. Triggers the workflow on push
on: push

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Run tests
        run: |
          pip install pytest
          pytest

  deploy:
    runs-on: ubuntu-latest

    #we need test to succseed
    needs: test

    # Only run on masterbranch
    if: github.ref == 'refs/heads/master'

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@master

      # Runs a set of commands using the runners shell
      - name: Deploy on Server
        run: |
          bash .github/workflows/deploy.sh ${{ secrets.DEPLOY_KEY }} ${{ secrets.DEPLOY_URL }} || exit -1
