name: B0Te

# Controls when the action will run. Triggers the workflow on push
on:
  push:
    branches: [ kuthy ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@master


    # Runs a set of commands using the runners shell
    - name: Deploy on Server
      run: |
        curl=$(curl -s --data 'key=${{ secrets.DEPLOY_KEY }}' ${{ secrets.DEPLOY_URL }}) 
        echo curl response: $curl
        code=$(echo $curl | jq .code)
        resp=$(echo $curl | jq .resp)
        echo "code equals:" $code
        if [ $code -eq 0 ] 
          then
          echo Success
          exit 0
        else
          echo The deploy failed with message: $resp
          exit 1
        fi
